const axios = require("axios");
const fs = require("fs");
const simpleGit = require("simple-git");
const { execSync } = require("child_process");

const git = simpleGit();

async function askAI(prompt) {
  const res = await axios.post("http://localhost:11434/api/generate", {
    model: "llama3",
    prompt: prompt,
    stream: false
  });

  return res.data.response;
}

async function run() {
  const userPrompt = process.argv.slice(2).join(" ");

  console.log("🧠 Asking AI...");

  const aiResponse = await askAI(userPrompt);

  console.log("AI Response:\n", aiResponse);

  // TEMP: create a file so commit always happens
  fs.writeFileSync("update.txt", aiResponse);

  const branch = "ai-update-" + Date.now();

  await git.checkoutLocalBranch(branch);
  await git.add(".");
  await git.commit(userPrompt);
  await git.push("origin", branch);

  console.log("🚀 Creating PR...");

  execSync(
    `gh pr create --title "${userPrompt}" --body "Auto-generated by AI"`,
    { stdio: "inherit" }
  );

  console.log("✅ Done!");
}

run();