workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Enable iOS
        script: flutter create .

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - your-email@example.com
