name: expense_manager
description: Personal Expense Manager

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.18.1
  home_widget: ^0.5.0
  flutter_sms_inbox: ^1.0.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  excel: ^4.0.6
  file_picker: ^8.0.5
  path_provider: ^2.1.4


flutter:
  uses-material-design: true
