name: Generate Keystore
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v \
            -keystore fintrack.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias fintrack \
            -dname "CN=FinTrack, OU=App, O=Vivek, L=India, S=India, C=IN" \
            -storepass fintrack123 \
            -keypass fintrack123

      - name: Convert to base64
        run: base64 -w 0 fintrack.jks > fintrack_base64.txt

      - name: Upload keystore
        uses: actions/upload-artifact@v6
        with:
          name: keystore
          path: |
            fintrack.jks
            fintrack_base64.txt
